import type {
  ActionType,
  InteractiveSceneObject,
  ObjectCategory,
  ObjectTransition,
} from "../shared/types";
import {
  initialVisualStateFor,
  isAllowedVisualState,
  visualStatesFor,
} from "./objectRuntime";

type ObjectSeed = {
  id: string;
  prefabId?: string;
  name: string;
  description: string;
  category: ObjectCategory;
  x: number;
  y: number;
  width?: number;
  height?: number;
  z?: number;
  radius?: number;
  states?: string[];
  actions?: ActionType[];
  stateActions?: Record<string, ActionType[]>;
  tags?: string[];
  facts?: Record<string, boolean | number | string>;
  transitions?: ObjectTransition[];
  discoverable?: boolean;
  enabled?: boolean;
};

const observeTransition = (name: string): ObjectTransition => ({
  actionType: "OBSERVE",
  resultSummary: `仔细观察了${name}`,
  animationCue: "actor_look",
});

const createObject = (seed: ObjectSeed): InteractiveSceneObject => {
  const normalizedTransitions = [
    observeTransition(seed.name),
    ...(seed.transitions ?? []),
  ].map((transition) => ({
    ...transition,
    ...(transition.fromStates
      ? {
          fromStates: transition.fromStates.filter((state) =>
            isAllowedVisualState(seed.id, state),
          ),
        }
      : {}),
    toState:
      transition.toState &&
      isAllowedVisualState(seed.id, transition.toState)
        ? transition.toState
        : undefined,
  }));

  return {
    id: seed.id,
    prefabId: seed.prefabId ?? seed.id,
    displayName: seed.name,
    description: seed.description,
    sceneId: "melon_street",
    category: seed.category,
    position: { x: seed.x, y: seed.y },
    size: { width: seed.width ?? 8, height: seed.height ?? 8 },
    zIndex: seed.z ?? Math.round(seed.y),
    currentVisualState: initialVisualStateFor(seed.id),
    availableVisualStates: [...visualStatesFor(seed.id)],
    interactionRadius: seed.radius ?? 12,
    enabled: seed.enabled ?? true,
    discoverable: seed.discoverable ?? false,
    discovered: !(seed.discoverable ?? false),
    tags: seed.tags ?? [],
    supportedActions: seed.actions ?? ["OBSERVE"],
    stateActionOverrides: seed.stateActions,
    facts: seed.facts ?? {},
    localMemory: [],
    transitions: normalizedTransitions,
  };
};

export const MELON_STREET_OBJECTS: InteractiveSceneObject[] = [
  createObject({
    id: "melon_single",
    prefabId: "melon",
    name: "西瓜",
    description: "一个纹路清楚、被老板摆在最前面的西瓜。",
    category: "PROP",
    x: 48,
    y: 49,
    width: 6,
    height: 6,
    z: 68,
    states: ["HELD", "ON_SCALE", "CUT_RIPE", "CUT_UNRIPE", "BROKEN", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "HOLD", "WEIGH", "CUT", "MOVE"],
    stateActions: {
      BROKEN: ["OBSERVE", "INSPECT", "MOVE"],
      CUT_RIPE: ["OBSERVE", "INSPECT", "SHOW_EVIDENCE"],
      CUT_UNRIPE: ["OBSERVE", "INSPECT", "SHOW_EVIDENCE"],
      ON_SCALE: ["OBSERVE", "INSPECT", "WEIGH", "MOVE"],
    },
    tags: ["melon", "food", "weighable", "cuttable"],
    facts: { ripeness: "unknown", paid: false },
    transitions: [
      {
        actionType: "HOLD",
        fromStates: ["DEFAULT"],
        toState: "HELD",
        resultSummary: "把西瓜抱了起来",
        animationCue: "actor_hold",
      },
      {
        actionType: "WEIGH",
        fromStates: ["DEFAULT", "HELD"],
        toState: "ON_SCALE",
        requiredFacts: ["scale_available"],
        resultSummary: "把西瓜放到了台秤上",
        animationCue: "actor_place",
      },
      {
        actionType: "CUT",
        fromStates: ["DEFAULT", "HELD"],
        toState: "CUT_RIPE",
        requiredFacts: ["knife_available"],
        setsFacts: { ripeness: "ripe" },
        revealsFacts: ["melon_is_ripe"],
        tensionDelta: 4,
        resultSummary: "切开西瓜，露出了鲜红的瓜瓤",
        animationCue: "actor_cut",
      },
      {
        actionType: "MOVE",
        fromStates: ["DEFAULT", "HELD", "ON_SCALE"],
        toState: "REMOVED",
        resultSummary: "把这只西瓜搬离了瓜摊",
        animationCue: "actor_carry",
      },
    ],
  }),
  createObject({
    id: "melon_pile",
    prefabId: "melon_pile",
    name: "西瓜堆",
    description: "大小不同的西瓜堆成半人高，底下压着旧草垫。",
    category: "CONTAINER",
    x: 39,
    y: 44,
    width: 14,
    height: 12,
    z: 60,
    states: ["DISTURBED", "EMPTY"],
    actions: ["OBSERVE", "INSPECT", "MOVE"],
    tags: ["melon", "container", "searchable"],
    transitions: [
      {
        actionType: "INSPECT",
        fromStates: ["DEFAULT"],
        toState: "DISTURBED",
        revealsFacts: ["melon_pile_has_old_receipt"],
        resultSummary: "翻看瓜堆，在草垫下发现一张旧收据",
        animationCue: "actor_search",
      },
    ],
  }),
  createObject({
    id: "hao_scale",
    prefabId: "scale",
    name: "瓜摊台秤",
    description: "指针有些迟钝的机械台秤，秤盘边缘磨得发亮。",
    category: "TOOL",
    x: 61,
    y: 46,
    width: 8,
    height: 10,
    z: 70,
    states: ["LOADED", "TAMPERED", "MAGNET_REVEALED", "BROKEN", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "WEIGH", "MOVE", "QUESTION", "SHOW_EVIDENCE", "REPAIR"],
    stateActions: {
      MAGNET_REVEALED: ["OBSERVE", "SHOW_EVIDENCE", "QUESTION", "MOVE"],
      BROKEN: ["OBSERVE", "INSPECT", "REPAIR", "MOVE", "QUESTION"],
      LOADED: ["OBSERVE", "INSPECT", "WEIGH", "QUESTION"],
    },
    tags: ["scale", "tool", "evidence", "weighing"],
    facts: { calibrated: false, contains_magnet: true },
    transitions: [
      {
        actionType: "WEIGH",
        fromStates: ["DEFAULT", "TAMPERED"],
        toState: "LOADED",
        setsFacts: { last_reading: "suspicious" },
        revealsFacts: ["melon_weight_is_suspicious"],
        tensionDelta: 4,
        dialogueShouldContinue: true,
        resultSummary: "重新称瓜，指针仍然明显偏重",
        animationCue: "scale_bounce",
      },
      {
        actionType: "INSPECT",
        fromStates: ["DEFAULT", "LOADED", "TAMPERED"],
        toState: "MAGNET_REVEALED",
        setsFacts: { magnet_revealed: true },
        revealsFacts: ["scale_contains_magnet"],
        objectStateChanges: { hidden_magnet: "REVEALED" },
        tensionDelta: 12,
        dialogueShouldContinue: true,
        resultSummary: "从台秤底部发现并取出了吸铁石",
        animationCue: "actor_reveal",
      },
      {
        actionType: "REPAIR",
        fromStates: ["BROKEN", "TAMPERED", "MAGNET_REVEALED"],
        toState: "DEFAULT",
        setsFacts: { calibrated: true, contains_magnet: false },
        requiredFacts: ["repair_tools_available"],
        resultSummary: "重新校准了台秤",
        animationCue: "actor_repair",
      },
      {
        actionType: "SHOW_EVIDENCE",
        fromStates: ["MAGNET_REVEALED"],
        requiredFacts: ["scale_contains_magnet"],
        tensionDelta: 15,
        dialogueShouldContinue: true,
        resultSummary: "把台秤的问题展示给围观者",
        animationCue: "actor_present",
      },
    ],
  }),
  createObject({
    id: "hidden_magnet",
    prefabId: "magnet",
    name: "吸铁石",
    description: "吸在秤底的黑色磁铁，不弯腰几乎看不见。",
    category: "EVIDENCE",
    x: 62,
    y: 51,
    width: 4,
    height: 3,
    z: 72,
    states: ["REVEALED", "HELD", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "HOLD", "SHOW_EVIDENCE"],
    tags: ["evidence", "magnet", "hidden"],
    discoverable: true,
    transitions: [
      {
        actionType: "HOLD",
        fromStates: ["DEFAULT", "REVEALED"],
        toState: "HELD",
        inventoryAdds: ["hidden_magnet"],
        revealsFacts: ["scale_contains_magnet"],
        resultSummary: "把吸铁石收进了手里",
        animationCue: "actor_pickup",
      },
    ],
  }),
  createObject({
    id: "scale_weight",
    prefabId: "scale_weight",
    name: "砝码",
    description: "一组常用砝码，表面沾着黑色油渍。",
    category: "TOOL",
    x: 66,
    y: 48,
    width: 4,
    height: 4,
    z: 71,
    states: ["HELD", "ON_SCALE", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "HOLD", "WEIGH"],
    tags: ["tool", "weight", "calibration"],
    transitions: [
      {
        actionType: "WEIGH",
        toState: "ON_SCALE",
        revealsFacts: ["scale_calibration_is_wrong"],
        resultSummary: "用标准砝码复验了台秤",
        animationCue: "actor_place",
      },
    ],
  }),
  createObject({
    id: "melon_knife",
    prefabId: "knife",
    name: "瓜刀",
    description: "刀口反着光，木柄被汗水浸得发黑。",
    category: "TOOL",
    x: 57,
    y: 52,
    width: 6,
    height: 3,
    z: 73,
    states: ["HELD", "ON_BOARD", "DULL", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "HOLD", "CUT", "MOVE"],
    tags: ["tool", "knife", "cutting"],
    facts: { available: true },
    transitions: [
      {
        actionType: "HOLD",
        fromStates: ["DEFAULT", "ON_BOARD"],
        toState: "HELD",
        setsFacts: { held_by_actor: true },
        revealsFacts: ["knife_available"],
        resultSummary: "拿起了砧板旁的瓜刀",
        animationCue: "actor_pickup",
      },
    ],
  }),
  createObject({
    id: "chopping_board",
    prefabId: "board",
    name: "砧板",
    description: "厚木砧板上满是深浅不一的刀痕。",
    category: "TOOL",
    x: 55,
    y: 51,
    width: 8,
    height: 5,
    z: 67,
    states: ["OCCUPIED", "WET", "BROKEN"],
    actions: ["OBSERVE", "INSPECT", "USE"],
    tags: ["tool", "board", "cutting"],
  }),
  createObject({
    id: "wooden_table",
    prefabId: "table",
    name: "木桌",
    description: "瓜摊的旧木桌，一条桌腿垫着折叠纸片。",
    category: "FURNITURE",
    x: 55,
    y: 47,
    width: 22,
    height: 9,
    z: 50,
    states: ["CLEARED", "DAMAGED", "REPAIRED"],
    actions: ["OBSERVE", "INSPECT", "MOVE", "REPAIR"],
    tags: ["furniture", "surface"],
  }),
  createObject({
    id: "short_stool",
    prefabId: "stool",
    name: "矮凳",
    description: "一把矮木凳，凳面被磨得发白。",
    category: "FURNITURE",
    x: 70,
    y: 58,
    width: 6,
    height: 7,
    states: ["OCCUPIED", "FALLEN", "BROKEN"],
    actions: ["OBSERVE", "INSPECT", "SIT", "MOVE", "REPAIR"],
    stateActions: {
      OCCUPIED: ["OBSERVE", "SIT", "MOVE", "QUESTION"],
      FALLEN: ["OBSERVE", "INSPECT", "MOVE", "REPAIR"],
      BROKEN: ["OBSERVE", "INSPECT", "MOVE", "REPAIR"],
    },
    tags: ["furniture", "seat"],
    transitions: [
      {
        actionType: "SIT",
        fromStates: ["DEFAULT"],
        toState: "OCCUPIED",
        resultSummary: "在矮凳上坐了下来",
        animationCue: "actor_sit",
      },
      {
        actionType: "MOVE",
        fromStates: ["DEFAULT", "OCCUPIED"],
        toState: "FALLEN",
        resultSummary: "矮凳被挪开后侧翻在地",
        animationCue: "object_fall",
      },
    ],
  }),
  createObject({
    id: "sunshade_canopy",
    prefabId: "canopy",
    name: "遮阳棚",
    description: "红白条纹的旧棚布，把瓜摊切成明暗两半。",
    category: "BUILDING",
    x: 53,
    y: 30,
    width: 40,
    height: 14,
    states: ["FOLDED", "TORN", "WET", "REPAIRED"],
    actions: ["OBSERVE", "INSPECT", "OPEN", "REPAIR"],
    tags: ["building", "cover", "weather"],
  }),
  createObject({
    id: "wooden_crate",
    prefabId: "crate",
    name: "木箱",
    description: "钉着铁皮角的木箱，箱缝里卡着一张货签。",
    category: "CONTAINER",
    x: 33,
    y: 55,
    width: 9,
    height: 9,
    states: ["OPEN", "EMPTY", "BROKEN"],
    actions: ["OBSERVE", "INSPECT", "OPEN", "MOVE"],
    tags: ["container", "searchable"],
    transitions: [
      {
        actionType: "OPEN",
        fromStates: ["DEFAULT"],
        toState: "OPEN",
        revealsFacts: ["crate_has_supplier_tag"],
        resultSummary: "打开木箱，看到夹在箱缝里的供货标签",
        animationCue: "object_open",
      },
    ],
  }),
  createObject({
    id: "price_sign",
    prefabId: "sign",
    name: "价格牌",
    description: "纸板上用粗笔写着瓜价，最后一笔明显改过。",
    category: "EVIDENCE",
    x: 47,
    y: 39,
    width: 7,
    height: 7,
    states: ["TURNED", "TORN", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "QUESTION", "SHOW_EVIDENCE", "MOVE"],
    tags: ["sign", "price", "evidence", "canon"],
    facts: { price_per_jin: 2, altered: true },
    transitions: [
      {
        actionType: "INSPECT",
        revealsFacts: ["price_sign_was_altered"],
        resultSummary: "发现价格牌上的数字被人改写过",
        animationCue: "actor_inspect",
      },
    ],
  }),
  createObject({
    id: "vendor_stall",
    prefabId: "stall",
    name: "瓜摊",
    description: "占着街角的临时瓜摊，木板和帆布拼得很结实。",
    category: "BUILDING",
    x: 53,
    y: 43,
    width: 43,
    height: 25,
    z: 28,
    states: ["OPEN", "CLOSED", "DAMAGED", "INSPECTION", "EMPTY", "REPAIRED"],
    actions: ["OBSERVE", "INSPECT", "QUESTION", "NEGOTIATE", "REPAIR"],
    stateActions: {
      CLOSED: ["OBSERVE", "QUESTION", "NEGOTIATE"],
      DAMAGED: ["OBSERVE", "INSPECT", "REPAIR", "QUESTION"],
      EMPTY: ["OBSERVE", "INSPECT", "QUESTION"],
    },
    tags: ["stall", "building", "market"],
  }),
  createObject({
    id: "motorcycle",
    prefabId: "motorcycle",
    name: "摩托车",
    description: "一辆沾着尘土的旧摩托，钥匙不在车上。",
    category: "VEHICLE",
    x: 80,
    y: 66,
    width: 14,
    height: 9,
    states: ["RIDING", "DAMAGED", "ABSENT"],
    actions: ["OBSERVE", "INSPECT", "RIDE", "MOVE", "REPAIR"],
    stateActions: {
      DAMAGED: ["OBSERVE", "INSPECT", "MOVE", "REPAIR"],
      ABSENT: ["OBSERVE", "QUESTION"],
    },
    tags: ["vehicle", "exit"],
    facts: { has_key: false },
    transitions: [
      {
        actionType: "RIDE",
        fromStates: ["DEFAULT"],
        toState: "RIDING",
        requiredFacts: ["motorcycle_key_found"],
        resultSummary: "发动摩托驶离了街口",
        animationCue: "vehicle_depart",
      },
    ],
  }),
  createObject({
    id: "bicycle",
    prefabId: "bicycle",
    name: "自行车",
    description: "靠墙的二八自行车，车铃轻轻晃着。",
    category: "VEHICLE",
    x: 87,
    y: 45,
    width: 10,
    height: 10,
    states: ["RIDING", "FALLEN", "DAMAGED", "ABSENT"],
    actions: ["OBSERVE", "INSPECT", "RIDE", "MOVE", "REPAIR"],
    tags: ["vehicle", "street"],
  }),
  createObject({
    id: "utility_pole",
    prefabId: "utility_pole",
    name: "电线杆",
    description: "贴满小广告的水泥电线杆，顶端电线嗡嗡作响。",
    category: "DECORATION",
    x: 91,
    y: 29,
    width: 5,
    height: 33,
    actions: ["OBSERVE", "INSPECT"],
    tags: ["street", "landmark"],
  }),
  createObject({
    id: "wall_ad",
    prefabId: "wall_ad",
    name: "墙面广告",
    description: "褪色的旧广告，边角被雨水泡得卷起。",
    category: "DECORATION",
    x: 16,
    y: 34,
    width: 13,
    height: 12,
    states: ["TORN", "REMOVED"],
    actions: ["OBSERVE", "INSPECT", "QUESTION"],
    tags: ["decoration", "clue"],
    transitions: [
      {
        actionType: "INSPECT",
        revealsFacts: ["wall_ad_covers_old_mark"],
        resultSummary: "从卷起的广告边缘看见墙上的旧记号",
        animationCue: "actor_inspect",
      },
    ],
  }),
  createObject({
    id: "shop_door",
    prefabId: "door",
    name: "店铺门",
    description: "瓜摊后方的卷帘门，里面偶尔传来收音机声。",
    category: "PORTAL",
    x: 24,
    y: 35,
    width: 12,
    height: 22,
    states: ["OPEN", "CLOSED", "LOCKED"],
    actions: ["OBSERVE", "INSPECT", "OPEN", "QUESTION"],
    tags: ["portal", "shop"],
  }),
  createObject({
    id: "drainage_ditch",
    prefabId: "ditch",
    name: "排水沟",
    description: "沿路边延伸的浅沟，水面漂着几片瓜籽。",
    category: "DECORATION",
    x: 49,
    y: 78,
    width: 58,
    height: 5,
    states: ["BLOCKED", "CLEARED", "WET"],
    actions: ["OBSERVE", "INSPECT", "MOVE"],
    tags: ["street", "water", "clue"],
  }),
  createObject({
    id: "trash_bin",
    prefabId: "trash_bin",
    name: "垃圾桶",
    description: "绿色塑料桶盖没有完全合上，旁边落着一张纸团。",
    category: "CONTAINER",
    x: 12,
    y: 62,
    width: 7,
    height: 9,
    states: ["OPEN", "CLOSED", "OVERTURNED", "EMPTY"],
    actions: ["OBSERVE", "INSPECT", "OPEN", "MOVE"],
    tags: ["container", "searchable"],
    transitions: [
      {
        actionType: "OPEN",
        fromStates: ["DEFAULT", "CLOSED"],
        toState: "OPEN",
        revealsFacts: ["trash_has_weight_ticket"],
        resultSummary: "打开垃圾桶，找到一张揉皱的称重票",
        animationCue: "object_open",
      },
    ],
  }),
  createObject({
    id: "public_phone",
    prefabId: "phone",
    name: "公用电话",
    description: "装在小卖部墙边的投币电话，听筒线缠了胶布。",
    category: "TOOL",
    x: 8,
    y: 42,
    width: 7,
    height: 12,
    states: ["IN_USE", "BROKEN", "OFF_HOOK"],
    actions: ["OBSERVE", "INSPECT", "CALL", "REPAIR"],
    tags: ["phone", "communication"],
    facts: { requires_coin: true },
  }),
  createObject({
    id: "road_exit",
    prefabId: "road_exit",
    name: "道路出口",
    description: "街道通向更热闹的市场深处，远处人声混成一片。",
    category: "PORTAL",
    x: 96,
    y: 74,
    width: 8,
    height: 18,
    actions: ["OBSERVE", "LEAVE", "WAIT"],
    tags: ["portal", "exit"],
    radius: 16,
  }),
];

export const OBJECTS_BY_ID = Object.fromEntries(
  MELON_STREET_OBJECTS.map((object) => [object.id, object]),
) as Record<string, InteractiveSceneObject>;

export const getSceneObjects = (sceneId: string): InteractiveSceneObject[] =>
  MELON_STREET_OBJECTS.filter((object) => object.sceneId === sceneId);
